### ISSUE TITLE
服务不能正常上线

### ISSUE THREAD

**Issue by HiFxs** [3ylh3/netty-rpc#1]
我是按照你的步骤把项目打包在部署到其他项目。
标记一个服务：
```
@Service
public class TestService implements Test {

    @Override
    public String test(String message) {
        return "hello " + message;
    }
}
```
然后项目是一个sprinbboot,主启动类启动后，nacos中并没有发现该服务（spring.yml中也配置了相关信息。）
不知道问题出在了哪块？

**Comment by 3ylh3** [comment]
可以把测试工程代码打包贴一份吗

**Comment by HiFxs** [comment]
[Uploading Graduate.zip…]()

**Comment by 3ylh3** [comment]
没看到呢，或者你传到github上给我贴个链接把

**Comment by HiFxs** [comment]
[https://github.com/HiFxs/RPC_test](url)

**Comment by 3ylh3** [comment]
发现了两个问题：
1.你的pom文件里没有引com.xiaobai.netty-rpc的依赖包呢。
2.application.protites配置文件里需要有spring.application.name配置项。

**Comment by HiFxs** [comment]
jar包我直接外部引入的

**Comment by 3ylh3** [comment]
那你在配置文件里加上spring.application.name配置项再试试，没有的话应该是启动不起来的，我把你的代码下下来试了试是可以的，只不过我改成springboot2.7.1了。

**Comment by HiFxs** [comment]
我换成2.7.1后报了一个错误：
Field registry in com.xiaobai.nettyrpc.common.config.CommonAutoConfiguration required a bean of type 'io.micrometer.prometheus.PrometheusMeterRegistry' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'io.micrometer.prometheus.PrometheusMeterRegistry' in your configuration.

**Comment by HiFxs** [comment]
你的源代码中有一项：
    @Autowired
    private PrometheusMeterRegistry registry;
好像不能正常注入，我IDEA这一项是报错的

**Comment by 3ylh3** [comment]
直接引外部jar包可能会有问题，你install到本地仓库，通过pom文件去引netty-rpc的依赖就可以了。

**Comment by HiFxs** [comment]
抱歉，下午有点其他事没能及时回复。
问题解决了，直接引入的方式确实有问题，应该是很多依赖引入不全。
我pom文件引入后依靠本地仓库能修复好这些依赖。
另外springboot3.X确实不能启动， 2.X的版本能兼容。
再次谢谢你的耐心解答！

**Comment by 3ylh3** [comment]
ok
